import assert from 'node:assert/strict';
import { describe, it } from 'node:test';
import { defaultConfig, defaultPhase } from '../defaults.js';
import { FIRMWARE_LEGACY } from '../firmware-profile.js';
import { loadPlannerSnapshot } from '../snapshots.js';
import type { PhaseConfig } from '../types.js';
import { forecast, recordingCurrentMa, audioProcessingIntervalSeconds, opusEncodeMs, magnetAverageMa } from './forecast.js';

/**
 * The expected figures below are the spreadsheet's OWN computed outputs, read from
 * `reference/planner-snapshot.json` (generated by
 * tools/extract_power_measurements.py from Planner!L4:N8 and Planner!L12:N16).
 *
 * Reading them from the snapshot rather than hardcoding them means a spreadsheet
 * revision automatically becomes the new expectation: these tests then fail only if
 * the PORT disagrees with the SHEET, which is the only thing worth asserting.
 */
const SNAPSHOT = loadPlannerSnapshot();

const SHEET_INPUTS = {
  sdSpeedClass: SNAPSHOT.plannerInputs.sdSpeedClass,
  microphone: SNAPSHOT.plannerInputs.microphone,
  imuSampleRateHz: SNAPSHOT.plannerInputs.imuSampleRateHz,
  // The spreadsheet's own storage model: GB x 1024^3 of pure bytes, with no filesystem.
  // The dashboard's default charges clusters, directories, and logs; parity is with the sheet.
  storageModel: 'raw' as const,
};

const CLIP_LENGTH_S = SNAPSHOT.plannerInputs.storedClipLengthSeconds;

function continuousPhase(overrides: Partial<PhaseConfig> = {}): PhaseConfig {
  return {
    ...defaultPhase(),
    audioRecordingMode: 'CONTINUOUS',
    audioClipLengthSeconds: CLIP_LENGTH_S,
    imuRecordingMode: 'AUDIO',
    imuSampleRateHz: 50,
    ...overrides,
  };
}

describe('recordingCurrentMa — uncompressed WAV (Planner!L4:L8)', () => {
  for (const row of SNAPSHOT.goldenWav) {
    it(`${row.sampleRateHz} Hz draws ${row.averageCurrentMa.toFixed(4)} mA`, () => {
      const actual = recordingCurrentMa(
        continuousPhase({ audioSampleRateHz: row.sampleRateHz, useOpusEncoding: false }),
        SHEET_INPUTS,
      );
      assert.ok(
        Math.abs(actual - row.averageCurrentMa) < 1e-9,
        `expected ${row.averageCurrentMa}, got ${actual} ` +
          `(delta ${Math.abs(actual - row.averageCurrentMa)})`,
      );
    });
  }
});

describe('recordingCurrentMa — Ogg Opus at 48 kHz (Planner!L12:L16)', () => {
  for (const row of SNAPSHOT.goldenOpus) {
    it(`${row.bitrateKbps} kbps draws ${row.averageCurrentMa.toFixed(4)} mA`, () => {
      const actual = recordingCurrentMa(
        continuousPhase({ useOpusEncoding: true, opusBitrate: row.bitrateKbps * 1000 }),
        SHEET_INPUTS,
      );
      assert.ok(
        Math.abs(actual - row.averageCurrentMa) < 1e-9,
        `expected ${row.averageCurrentMa}, got ${actual} ` +
          `(delta ${Math.abs(actual - row.averageCurrentMa)})`,
      );
    });
  }
});

describe('storage and battery life (Planner!M and !N)', () => {
  // Planner!M = FLOOR(cardBytes / (audioBytesPerSec + imuBytesPerSec) / 86400)
  // Planner!N = FLOOR(batterymAh / avgCurrent / 24)
  for (const row of SNAPSHOT.goldenWav) {
    it(`${row.sampleRateHz} Hz lasts ${row.storageDays} days on card and ${row.batteryDays} on battery`, () => {
      const config = defaultConfig('UTC');
      config.ledsEnabled = false; // the sheet models neither LEDs nor VHF
      config.vhfMode = 'NEVER';
      config.phases = [continuousPhase({ audioSampleRateHz: row.sampleRateHz })];

      const result = forecast({
        config,
        ...SHEET_INPUTS,
        sdCardCapacityGb: SNAPSHOT.plannerInputs.sdCardCapacityGb,
        batteryCapacityMah: SNAPSHOT.plannerInputs.batteryCapacityMah,
      });
      assert.equal(Math.floor(result.storageDays), row.storageDays);
      assert.equal(Math.floor(result.batteryDays), row.batteryDays);
    });
  }
});

describe('audioProcessingIntervalSeconds (Planner!E)', () => {
  it('matches the sheet for every listed rate at a 60 s clip', () => {
    assert.equal(audioProcessingIntervalSeconds(8000, 60), 12);
    assert.equal(audioProcessingIntervalSeconds(16000, 60), 6);
    assert.equal(audioProcessingIntervalSeconds(24000, 60), 4);
    assert.equal(audioProcessingIntervalSeconds(32000, 60), 3);
    assert.equal(audioProcessingIntervalSeconds(48000, 60), 2);
  });

  it('never exceeds the clip length', () => {
    // A 5 s clip at 8 kHz could buffer 12 s, but there is only 5 s to buffer.
    assert.equal(audioProcessingIntervalSeconds(8000, 5), 5);
  });

  it('falls back to a divisor of the clip length', () => {
    // 96000/16000 = 6 s of buffer, but 7 is not divisible by 6, so step down to 1.
    assert.equal(audioProcessingIntervalSeconds(16000, 7), 1);
  });
});

describe('magnetAverageMa (MagPower!E6)', () => {
  it('matches the sheet', () => {
    assert.ok(Math.abs(magnetAverageMa() - 5.0443611111111112e-4) < 1e-15);
  });
});

describe('opusEncodeMs', () => {
  it('returns the measured values at the measured bitrates', () => {
    assert.equal(opusEncodeMs(16000), 521);
    assert.equal(opusEncodeMs(128000), 895);
  });

  it('interpolates between them', () => {
    assert.equal(opusEncodeMs(48000), (684 + 813) / 2);
  });

  it('clamps outside the measured range', () => {
    assert.equal(opusEncodeMs(5000), 521);
    assert.equal(opusEncodeMs(256000), 895);
  });
});

describe('duty cycle extensions (beyond the spreadsheet)', () => {
  it('halves storage for a 12-hour daily schedule', () => {
    const config = defaultConfig('UTC');
    config.ledsEnabled = false;
    config.vhfMode = 'NEVER';
    config.phases = [
      continuousPhase({
        audioRecordingMode: 'SCHEDULED',
        audioTriggerTimes: [{ startSecond: 0, endSecond: 43200 }],
      }),
    ];
    const result = forecast({ config, ...SHEET_INPUTS });
    assert.equal(result.perPhase[0].dutyCycle, 0.5);
  });

  it('treats a 10 s clip every 10 minutes as a 1/60 duty cycle', () => {
    const phase = continuousPhase({
      audioRecordingMode: 'INTERVAL',
      audioClipLengthSeconds: 10,
      audioTriggerInterval: 10,
      audioTriggerIntervalTimeScale: 'MINUTES',
    });
    const config = defaultConfig('UTC');
    config.ledsEnabled = false;
    config.vhfMode = 'NEVER';
    config.phases = [phase];
    const result = forecast({ config, ...SHEET_INPUTS });
    assert.ok(Math.abs(result.perPhase[0].dutyCycle - 10 / 600) < 1e-12);
  });

  it('treats a zero clip cap as unlimited, as current firmware does', () => {
    // Storage has to assume the worst case, which is recording continuously.
    const config = defaultConfig('UTC');
    config.phases = [continuousPhase({ audioRecordingMode: 'AMPLITUDE', maxAudioClips: 0 })];
    const result = forecast({ config, ...SHEET_INPUTS });
    assert.equal(result.perPhase[0].dutyCycle, 1);
    assert.ok(result.bytesPerDay > 0);
  });

  it('reports zero duty for a card read from firmware that disarmed on a zero cap', () => {
    const config = defaultConfig('UTC');
    config.phases = [continuousPhase({ audioRecordingMode: 'AMPLITUDE', maxAudioClips: 0 })];
    const result = forecast({ config, ...SHEET_INPUTS, firmware: FIRMWARE_LEGACY });
    assert.equal(result.perPhase[0].dutyCycle, 0);
    assert.equal(result.bytesPerDay, 0);
  });

  it('degrades confidence once an extrapolated value is involved', () => {
    const config = defaultConfig('UTC');
    config.ledsEnabled = false;
    config.vhfMode = 'NEVER';
    config.phases = [
      continuousPhase({
        audioRecordingMode: 'SCHEDULED',
        audioTriggerTimes: [{ startSecond: 0, endSecond: 3600 }],
      }),
    ];
    // A partial duty cycle pulls in the idle-state model, which is unmeasured.
    assert.equal(forecast({ config, ...SHEET_INPUTS }).confidence, 'extrapolated');
  });
});

/**
 * A phased deployment has no typical day, and the totals have to follow the phases in
 * the order they run rather than at their blended average rate.
 */
describe('phased deployments', () => {
  /** Two 10-day phases: the first recording continuously, the second half the day. */
  function twoPhases(): ReturnType<typeof defaultConfig> {
    const config = defaultConfig('UTC');
    config.ledsEnabled = false;
    config.vhfMode = 'NEVER';
    config.startTime = '2026-01-01T00:00:00.000Z';
    config.endTime = '2026-01-21T00:00:00.000Z';
    config.isPhased = true;
    config.phases = [
      continuousPhase({
        name: 'Loud',
        startTime: '2026-01-01T00:00:00.000Z',
        endTime: '2026-01-11T00:00:00.000Z',
      }),
      continuousPhase({
        name: 'Quiet',
        startTime: '2026-01-11T00:00:00.000Z',
        endTime: '2026-01-21T00:00:00.000Z',
        audioRecordingMode: 'SCHEDULED',
        audioTriggerTimes: [{ startSecond: 0, endSecond: 43200 }],
      }),
    ];
    return config;
  }

  it('reports a duration-weighted average day, not one phase or the other', () => {
    const result = forecast({ config: twoPhases(), ...SHEET_INPUTS, sdCardCapacityGb: 4096 });
    const [loud, quiet] = result.perPhase;
    assert.equal(quiet.bytesPerDay, loud.bytesPerDay / 2);
    // Equal halves of the deployment, so the average sits exactly between them.
    assert.ok(Math.abs(result.bytesPerDay - (loud.bytesPerDay + quiet.bytesPerDay) / 2) < 1e-6);
    assert.ok(Math.abs(result.clipsPerDay - (loud.clipsPerDay + quiet.clipsPerDay) / 2) < 1e-9);
  });

  it('counts clips phase by phase rather than from the average rate', () => {
    const result = forecast({ config: twoPhases(), ...SHEET_INPUTS, sdCardCapacityGb: 4096 });
    const [loud, quiet] = result.perPhase;
    assert.equal(result.cardFullAt, null);
    assert.equal(result.totalClips, Math.round((loud.clipsPerDay + quiet.clipsPerDay) * 10));
  });

  it('stops counting where the card fills, and fills it at the running rate', () => {
    const config = twoPhases();
    const full = forecast({ config, ...SHEET_INPUTS, sdCardCapacityGb: 4096 });
    // A card holding exactly five days of the FIRST phase must fill on day five —
    // at the deployment average it would appear to last well over six.
    const fiveDays = (full.perPhase[0].bytesPerDay * 5) / 1024 ** 3;
    const result = forecast({ config, ...SHEET_INPUTS, sdCardCapacityGb: fiveDays });

    assert.ok(Math.abs(result.storageDays - 5) < 1e-6, `filled at day ${result.storageDays}`);
    assert.equal(result.cardFullAt, '2026-01-06T00:00:00.000Z');
    assert.equal(result.totalClips, Math.round(full.perPhase[0].clipsPerDay * 5));
    assert.equal(result.cardUsedFraction, 1);
    assert.ok(Math.abs(result.totalBytes - fiveDays * 1024 ** 3) < 1e-3);
  });

  it('records nothing during a gap between phases', () => {
    const config = twoPhases();
    // Open a five-day hole in the middle by starting the second phase late.
    config.phases[1].startTime = '2026-01-16T00:00:00.000Z';
    const result = forecast({ config, ...SHEET_INPUTS, sdCardCapacityGb: 4096 });
    const [loud, quiet] = result.perPhase;
    assert.equal(result.totalClips, Math.round(loud.clipsPerDay * 10 + quiet.clipsPerDay * 5));
    // Fifteen recording days spread over twenty, so the average day is lighter.
    assert.ok(Math.abs(result.bytesPerDay - (loud.bytesPerDay * 10 + quiet.bytesPerDay * 5) / 20) < 1e-6);
  });
});

describe('what the dashboard shows, beyond the spreadsheet', () => {
  function dawnDusk(latitude: number | null): ReturnType<typeof defaultConfig> {
    const config = defaultConfig('America/Chicago');
    config.startTime = '2026-04-01T05:00:00.000Z';
    config.endTime = '2026-07-01T05:00:00.000Z';
    config.latitude = latitude;
    config.longitude = latitude === null ? null : -86.78;
    config.phases = [
      continuousPhase({
        audioRecordingMode: 'SCHEDULED',
        audioScheduleType: 'SOLAR',
        audioSolarWindows: [{ startAnchor: 'DAWN', startOffsetSeconds: 0, endAnchor: 'SUNRISE', endOffsetSeconds: 4 * 3600 }],
        audioTriggerTimes: [{ startSecond: 5 * 3600, endSecond: 6 * 3600 }],
      }),
    ];
    return config;
  }

  it('forecasts a solar schedule from the sun, not from its fallback', () => {
    const solar = forecast({ config: dawnDusk(36.16) });
    // Dawn to four hours after sunrise is roughly four and a half hours; the fallback is one.
    const hours = solar.perPhase[0].dutyCycle * 24;
    assert.ok(hours > 4 && hours < 5, `recorded ${hours} h a day`);
  });

  it('uses the fallback every day when the deployment has no position', () => {
    const fallback = forecast({ config: dawnDusk(null) });
    assert.ok(Math.abs(fallback.perPhase[0].dutyCycle * 24 - 1) < 1e-9);
    assert.ok(fallback.caveats.some((caveat) => caveat.includes('no position')));
  });

  it('forecasts continuous recording for a schedule with nothing to schedule by', () => {
    const config = defaultConfig('UTC');
    config.phases = [continuousPhase({ audioRecordingMode: 'SCHEDULED', audioTriggerTimes: [] })];
    assert.equal(forecast({ config }).perPhase[0].dutyCycle, 1);
  });

  it('charges the card whole clusters, so it holds less than the raw byte count suggests', () => {
    const config = defaultConfig('UTC');
    config.phases = [continuousPhase()];
    const exfat = forecast({ config });
    const raw = forecast({ config, storageModel: 'raw' });
    assert.ok(exfat.cardBytesPerDay > exfat.bytesPerDay);
    assert.ok(exfat.cardUsableBytes < raw.cardUsableBytes);
    assert.ok(exfat.allocationUnitBytes !== null);
  });

  it('stops counting clips where the battery runs out, as it does where the card fills', () => {
    const config = defaultConfig('UTC');
    config.startTime = '2026-01-01T00:00:00.000Z';
    config.endTime = '2026-03-02T00:00:00.000Z';
    config.phases = [continuousPhase()];
    const plenty = forecast({ config, sdCardCapacityGb: 4096, batteryCapacityMah: 1_000_000 });
    const small = forecast({ config, sdCardCapacityGb: 4096, batteryCapacityMah: 1000 });
    assert.equal(small.stopsEarlyBecause, 'battery');
    assert.ok(small.batteryDeadAt !== null);
    assert.ok(Math.abs(small.recordingDays - small.batteryDays) < 1e-9);
    assert.ok(Math.abs(small.totalClips - plenty.clipsPerDay * small.batteryDays) <= 1);
  });
});

describe('the VHF beacon', () => {
  it('draws nothing from the A3EM battery, since it has its own', () => {
    const config = defaultConfig('UTC');
    config.phases = [continuousPhase()];
    const without = forecast({ config: { ...config, vhfMode: 'NEVER' } });
    const withBeacon = forecast({ config: { ...config, vhfMode: 'SCHEDULED', vhfStartTime: config.startTime } });
    assert.equal(withBeacon.averageCurrentMa, without.averageCurrentMa);
    assert.ok(!withBeacon.caveats.some((caveat) => caveat.includes('VHF')));
  });
});
